name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        env:
          CI: false
        run: npm run build
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Login to Firebase
        run: firebase login:ci
        env:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKBOARD_4D88D }}
          channelId: live
          projectId: taskboard-4d88d
      - name: FireBase deploy 
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKBOARD_4D88D }}' > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKBOARD_4D88D }}
          channelId: live
          projectId: taskboard-4d88d
